Va 10 m
eScribers/twilio-video-app-react pull request #16
Opened 2020-11-11 10:18 UTC by chani3251

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [AHOYAPPS-0000](https://issues.corp.twilio.com/browse/AHOYAPPS-0000)

### Description

A description of what this PR does.

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Re-tested if necessary

2020-11-17 10:53 UTC, YehudaNewmanEScribers requested changes
main change here is to move the onmsg from useIsHostIn and controls to menubar.

2020-11-17 10:53 UTC, YehudaNewmanEScribers commented on src/components/Controls/Controls.tsx
> +//import useIsHostIn from '../../hooks/useIsHosetIn/useIsHostIn';
please delete the comment

2020-11-17 10:53 UTC, YehudaNewmanEScribers commented on src/components/Controls/Controls.tsx
> +      <ToggleVideoButton disabled={disableButtons} />
I agree with you that we can undo this line and return it to 
 "ToggleVideoButton disabled={isReconnecting} "
Infact, I think it should be undone because I don't see why a person shouldn't be able to be videoed.

2020-11-17 10:53 UTC, YehudaNewmanEScribers commented on src/debug.log
> +[1109/145027.444:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
please don't commit these things.
can you please add it to .gitignore. Thx.

2020-11-17 10:53 UTC, YehudaNewmanEScribers commented on src/hooks/useDisableToggleButtons/useDisableToggleButtons.tsx
> +import useIsHosetIn from '../useIsHosetIn/useIsHostIn';
There is a spelling mistake. It should be useIsHostIn rather than useIsHosetIn

2020-11-17 10:53 UTC, YehudaNewmanEScribers commented on src/hooks/useDisableToggleButtons/useDisableToggleButtons.tsx
> +        alert('Reporter has joind please unmute your microphon');
microphone not microphon
joined , not joind

2020-11-17 10:53 UTC, YehudaNewmanEScribers commented on src/hooks/useIsHosetIn/useIsHostIn.tsx
> +  if (typeof room.participants !== 'undefined' && room !== null) {
need to reverse the order of the conditions in this if statement

2020-11-17 10:53 UTC, YehudaNewmanEScribers commented on src/components/Controls/Controls.tsx
> +  const [notification, setNotification] = useState(null);
please try to use the existing notification dialog instead of a local copy of it.

2020-11-17 10:53 UTC, YehudaNewmanEScribers commented on src/hooks/useIsHostIn/useIsHosetIn.test.tsx
> +  it('should return true by default', () => {
seeing as this seems to test the case of when there are no participants yet can you change the description of the test

2020-11-17 10:53 UTC, YehudaNewmanEScribers commented on src/hooks/useIsHostIn/useIsHosetIn.test.tsx
> +    expect(onmsg).toBeCalledWith(NOTIFICATION_MESSAGE.WAITING_FOR_REPORTER);
you can remove the onMsg check here and from all the tests because the menubar will deal with it

2020-11-19 04:31 UTC, talr requested changes

2020-11-19 04:31 UTC, talr commented on .vscode/launch.json
> +        "url": "http://localhost:3001",
Why have we changed the port?

2020-11-19 04:31 UTC, talr commented on src/components/MenuBar/MenuBar.tsx
> +    } else if (!isHostIn) {
Do we need the if here?

2020-11-19 04:31 UTC, talr commented on src/components/MenuBar/MenuBar.tsx
> +      audioTrack?.disable();
Where is the audioTrack enable? - After asking the participant if he wants to enable his audio.

2020-11-19 04:31 UTC, talr commented on src/hooks/useIsHostIn/useIsHosetIn.test.tsx
> +      mockRoom.emit('participantConnected', 'newParticipant1@Reporter');
Why we have here newParitipant1?

2020-11-19 04:43 UTC, talr requested changes

2020-11-19 04:43 UTC, talr commented on src/components/Controls/Controls.tsx
> +  const disableButtons = isReconnecting ? isReconnecting : isdisconnected ? false : !isHostIn;
Please explain.
Can we split to simple condition ? true : false statements?

2020-11-25 10:59 UTC, YehudaNewmanEScribers approved these changes

2020-11-25 10:59 UTC, YehudaNewmanEScribers commented on src/hooks/useIsHostIn/useIsHosetIn.test.tsx
> +      mockRoom.emit('participantConnected', 'newParticipant1@Reporter');
That seems to be deliberate: It simulates the arrival of a second reporter to the room

2020-11-25 11:03 UTC, merged