CA-442-When-Conf-App-ended-and-user-logged-in-bring-the-user-to-TABula-main-screen1
eScribers/twilio-video-app-react pull request #27
Opened 2021-01-11 12:43 UTC by giladadon1997

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [AHOYAPPS-0000](https://issues.corp.twilio.com/browse/AHOYAPPS-0000)

### Description

A description of what this PR does.

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Re-tested if necessary

2021-01-11 14:34 UTC, talr requested changes
Why it is to merge-code branch and not to integration (develop) branch?
Tal

2021-01-12 08:39 UTC, talr requested changes

2021-01-12 08:39 UTC, talr commented on src/state/index.tsx
> +    if (endpoint === '' || environmentName === '') {
Can we replace all the console.log() which eScribers Logger?

2021-01-12 08:39 UTC, talr commented on src/state/index.tsx
> +      if (isRegistered) window.location.replace(decodedRedirectTabulaUrl);
Can we ident the code? i.e. this if statement

2021-01-12 08:39 UTC, talr commented on src/state/index.tsx
> +      var loginPageUrl = `http://tabula-${environmentName}.escribers.io/tabula/welcome/login`;
In production it is not escribers.io but escribers.net, please talk with Chana to get this from the deployment pipeline.

2021-01-12 08:43 UTC, giladadon1997 commented
> Why it is to merge-code branch and not to integration (develop) branch?
> Tal

merge-code branch is the develop, for now, we can change it, but we need to ask Chana before, because its depend in cicd pipeline

2021-01-12 08:43 UTC, giladadon1997 commented on src/state/index.tsx
> +    if (endpoint === '' || environmentName === '') {
yes, it is another story in next sprint

2021-01-12 08:45 UTC, giladadon1997 commented on src/state/index.tsx
> +      var loginPageUrl = `http://tabula-${environmentName}.escribers.io/tabula/welcome/login`;
I talked about it with Chana, at the moment the environments are not aligned so she told me to leave like this, later we will change.

2021-01-12 08:46 UTC, giladadon1997 commented on src/state/index.tsx
> +      if (isRegistered) window.location.replace(decodedRedirectTabulaUrl);
what line do you talk about?

2021-01-12 09:15 UTC, talr commented on src/state/index.tsx
> +      var loginPageUrl = `http://tabula-${environmentName}.escribers.io/tabula/welcome/login`;
@chani3251 Why not to do it correctly?

2021-01-12 12:17 UTC, merged