INF-198- Moved login cypress commands to authentication submodule
eScribers/twilio-video-app-react pull request #34
Opened 2021-02-01 17:07 UTC by Galzk

Please merge on authentication repo before this one so the tests will pass

2021-02-02 10:30 UTC, talr requested changes
Move all Authentication tests into authentication repository.
Implement test filenames naming convention.

2021-02-02 10:30 UTC, talr commented on cypress/integration/twilio-video.spec.js
> +                  cy.visit(conferenceUrlPath);
Move into the login function as loginUrlPath

2021-02-02 10:30 UTC, talr commented on cypress/integration/twilio-video.spec.js
> +                  cy.url().should('include', conferenceUrlPath);
Add after cy.login new command cy.visit(newConferenceUrlPath)

2021-02-02 10:30 UTC, talr commented on cypress/integration/twilio-video.spec.js
>                    let userName = Cypress.env('loginAdminUserName');
let managerUserName = Cypress.env('managerUserName')

2021-02-02 10:30 UTC, talr commented on cypress/integration/twilio-video.spec.js
>                    let password = Cypress.env('loginAdminPassword');
let managerPassword = Cypress.env('managerPassword')

2021-02-03 13:25 UTC, Jonniedev commented
Looks good.
Does it run without errors?

2021-02-03 13:49 UTC, Galzk commented
> 
> 
> Looks good.
> Does it run without errors?

2021-02-03 13:50 UTC, Galzk commented
Oh I miss-clicked

2021-02-03 15:34 UTC, Galzk commented
@talr What's our procedure on changing/adding env vars?
We've got 2 modifications
```
managerUserName
managerPassword
```
It was 
```
loginAdminUserName
loginAdminPassword
```
But I don't know if that's safe to remove or is it used across different projects

2021-02-07 09:48 UTC, talr approved these changes

2021-02-08 10:59 UTC, merged