CA-753 Added participant order function with test
eScribers/twilio-video-app-react pull request #56
Opened 2021-03-14 08:44 UTC by Galzk

Still need to test on the app **and add sort by join time**

2021-03-14 12:43 UTC, Galzk commented
We should test it before deployment

2021-03-18 10:50 UTC, Galzk reviewed
Tested and ready to be merged!

2021-03-18 10:50 UTC, Galzk commented on src/components/ParticipantStrip/ParticipantStripCollaboration/ParticipantStripCollaboration.tsx
> +  const unorderedParticipants = useParticipants();
Under @talr direction:
Create new hook that's called useSortedParticipants and move this functionality there

2021-03-19 10:03 UTC, talr requested changes

2021-03-19 10:03 UTC, talr commented on src/components/ParticipantStrip/ParticipantStripGrid/ParticipantStripGrid.test.tsx
> +import ParticipantStripGrid from './ParticipantStripGrid';
```suggestion
import ParticipantGrid from './ParticipantGrid';

```

2021-03-19 10:03 UTC, talr commented on src/components/ParticipantStrip/ParticipantStripGrid/ParticipantStripGrid.tsx
> +import sortParticipants from '../../../utils/sortParticipants';
Remove line

2021-03-19 10:03 UTC, talr commented on src/state/index.tsx
>      console.log(
Can we replace all console.log with eScribers logger? Which also write on the console and give us better observability.

2021-03-19 10:03 UTC, talr commented on src/state/index.tsx
>            console.log('response from fetch received');
Same

2021-03-21 08:54 UTC, Galzk commented on src/state/index.tsx
>      console.log(
Out of scope, we don't have a logger initialized in this project

2021-04-12 11:10 UTC, talr approved these changes

2021-04-19 13:56 UTC, merged